server:
  port: 8080
  servlet:
    context-path: /muahang88

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  sendGrid:
    apiKey: ${SENDGRID_API_KEY:DUMMY-SENDGRID_API_KEY}
    fromEmail: 2154050113huy@ou.edu.vn
    templateId: d-633cd44557264434b8e74be584e016cf
    verificationLink: http://localhost:8080/user/confirm-email




jwt:
  singerKey: ${singerKey}
  valid-duration: 3600 # in second
  refreshable-duration: 36000

payment:
  vnPAY:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "W4ZF5LA3"
    secretKey: "MU86A2BNK23HMKEMOLVXVXQKRD6KRTXQ"
    returnUrl: "http://localhost:8080/muahang88/payment/vn-pay-callback"
    version: "2.1.0"
    command: "pay"
    orderType: "other"